# Generated by Django 5.1.4 on 2024-12-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skill_images/'),
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_needed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_offered',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchange.skillcategory'),
        ),
        migrations.AddField(
            model_name='skill',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.skillprovider'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_needed',
            field=models.ManyToManyField(blank=True, related_name='needed_by_users', to='exchange.skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_offered',
            field=models.ManyToManyField(blank=True, related_name='offered_by_users', to='exchange.skill'),
        ),
    ]
