# Generated by Django 5.1.4 on 2024-12-28 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_skillcategory_skillprovider_remove_skill_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillprovider',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='skillprovider',
            name='last_name',
        ),
        migrations.AddField(
            model_name='skillprovider',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
