# Generated by Django 5.1.4 on 2025-01-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_remove_skillprovider_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='provider',
        ),
        migrations.AddField(
            model_name='skill',
            name='providers',
            field=models.ManyToManyField(blank=True, to='exchange.skillprovider'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(default='Default Skill Title', max_length=255),
        ),
    ]
