# Generated by Django 5.1.4 on 2025-01-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_page',
            field=models.ImageField(default='assets/default_images/default-cover.png', upload_to='cover_pages/'),
        ),
    ]
