# Generated by Django 5.1.4 on 2025-01-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_userprofile_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pages/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
