# Generated by Django 5.1.4 on 2025-01-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_userprofile_cover_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_page',
            field=models.ImageField(default='assets/default_images/default-cover.png', upload_to='cover_pages/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='assets/default_images/default-profile.png', upload_to='profile_pics/'),
        ),
    ]
