# Generated by Django 5.1.4 on 2025-01-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_alter_skillexchange_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillexchange',
            name='provider',
        ),
        migrations.AddField(
            model_name='skillexchange',
            name='providers',
            field=models.ManyToManyField(blank=True, to='exchange.skillprovider'),
        ),
    ]
