# Generated by Django 5.1.4 on 2025-02-05 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_remove_skillexchange_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('es', 'spanish'), ('fr', 'french'), ('en', 'english')], max_length=50)),
                ('skill_level', models.CharField(choices=[('beginer', 'Beginer'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('learning_goals', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
