# Generated by Django 5.1.4 on 2025-02-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50),
        ),
    ]
