# Generated by Django 5.1.4 on 2025-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_alter_userpreference_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_language',
            field=models.CharField(choices=[('es', 'Spanish'), ('fr', 'French'), ('en', 'English')], max_length=50),
        ),
    ]
