# Generated by Django 5.1.4 on 2025-02-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_alter_userpreference_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='learning_goals',
            field=models.TextField(default=''),
        ),
    ]
