# Generated by Django 5.1.4 on 2025-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_userpreferencedashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
