# Generated by Django 5.1.4 on 2025-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0021_skillexchange_blockchain_tx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=255, unique=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
