# Generated by Django 5.1.4 on 2025-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0022_blockchaincontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ethereum_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
