# Generated by Django 5.1.4 on 2025-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_blockchaincontract_deployer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcertification',
            name='on_chain_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
